spring:
  datasource:
    username: root
    password: 13850179569
    url: jdbc:mysql://localhost:3306/document
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  health:
    redis:
      enabled: false
server:
  port: 9000
