package com.example.demo.entity;

public class FilereceptionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filereceptions.FileID
     *
     * @mbggenerated
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filereceptions.UserID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filereceptions.FileID
     *
     * @return the value of filereceptions.FileID
     *
     * @mbggenerated
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filereceptions.FileID
     *
     * @param fileid the value for filereceptions.FileID
     *
     * @mbggenerated
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filereceptions.UserID
     *
     * @return the value of filereceptions.UserID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filereceptions.UserID
     *
     * @param userid the value for filereceptions.UserID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}