package com.example.demo.entity;

public class FilesWithBLOBs extends Files {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.TABLE_SCHEMA
     *
     * @mbggenerated
     */
    private byte[] tableSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.TABLE_NAME
     *
     * @mbggenerated
     */
    private byte[] tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.FULLTEXT_KEYS
     *
     * @mbggenerated
     */
    private byte[] fulltextKeys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.DELETED_ROWS
     *
     * @mbggenerated
     */
    private byte[] deletedRows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.UPDATE_COUNT
     *
     * @mbggenerated
     */
    private byte[] updateCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.CREATION_TIME
     *
     * @mbggenerated
     */
    private byte[] creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    private byte[] lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.LAST_ACCESS_TIME
     *
     * @mbggenerated
     */
    private byte[] lastAccessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.RECOVER_TIME
     *
     * @mbggenerated
     */
    private byte[] recoverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.TRANSACTION_COUNTER
     *
     * @mbggenerated
     */
    private byte[] transactionCounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.TABLE_ROWS
     *
     * @mbggenerated
     */
    private byte[] tableRows;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.AVG_ROW_LENGTH
     *
     * @mbggenerated
     */
    private byte[] avgRowLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.DATA_LENGTH
     *
     * @mbggenerated
     */
    private byte[] dataLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.MAX_DATA_LENGTH
     *
     * @mbggenerated
     */
    private byte[] maxDataLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.INDEX_LENGTH
     *
     * @mbggenerated
     */
    private byte[] indexLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.CREATE_TIME
     *
     * @mbggenerated
     */
    private byte[] createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.UPDATE_TIME
     *
     * @mbggenerated
     */
    private byte[] updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.CHECK_TIME
     *
     * @mbggenerated
     */
    private byte[] checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.CHECKSUM
     *
     * @mbggenerated
     */
    private byte[] checksum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILES.EXTRA
     *
     * @mbggenerated
     */
    private byte[] extra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FILE_NAME
     *
     * @return the value of FILES.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FILE_NAME
     *
     * @param fileName the value for FILES.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.TABLE_SCHEMA
     *
     * @return the value of FILES.TABLE_SCHEMA
     *
     * @mbggenerated
     */
    public byte[] getTableSchema() {
        return tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.TABLE_SCHEMA
     *
     * @param tableSchema the value for FILES.TABLE_SCHEMA
     *
     * @mbggenerated
     */
    public void setTableSchema(byte[] tableSchema) {
        this.tableSchema = tableSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.TABLE_NAME
     *
     * @return the value of FILES.TABLE_NAME
     *
     * @mbggenerated
     */
    public byte[] getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.TABLE_NAME
     *
     * @param tableName the value for FILES.TABLE_NAME
     *
     * @mbggenerated
     */
    public void setTableName(byte[] tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.FULLTEXT_KEYS
     *
     * @return the value of FILES.FULLTEXT_KEYS
     *
     * @mbggenerated
     */
    public byte[] getFulltextKeys() {
        return fulltextKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.FULLTEXT_KEYS
     *
     * @param fulltextKeys the value for FILES.FULLTEXT_KEYS
     *
     * @mbggenerated
     */
    public void setFulltextKeys(byte[] fulltextKeys) {
        this.fulltextKeys = fulltextKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.DELETED_ROWS
     *
     * @return the value of FILES.DELETED_ROWS
     *
     * @mbggenerated
     */
    public byte[] getDeletedRows() {
        return deletedRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.DELETED_ROWS
     *
     * @param deletedRows the value for FILES.DELETED_ROWS
     *
     * @mbggenerated
     */
    public void setDeletedRows(byte[] deletedRows) {
        this.deletedRows = deletedRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.UPDATE_COUNT
     *
     * @return the value of FILES.UPDATE_COUNT
     *
     * @mbggenerated
     */
    public byte[] getUpdateCount() {
        return updateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.UPDATE_COUNT
     *
     * @param updateCount the value for FILES.UPDATE_COUNT
     *
     * @mbggenerated
     */
    public void setUpdateCount(byte[] updateCount) {
        this.updateCount = updateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.CREATION_TIME
     *
     * @return the value of FILES.CREATION_TIME
     *
     * @mbggenerated
     */
    public byte[] getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.CREATION_TIME
     *
     * @param creationTime the value for FILES.CREATION_TIME
     *
     * @mbggenerated
     */
    public void setCreationTime(byte[] creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.LAST_UPDATE_TIME
     *
     * @return the value of FILES.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public byte[] getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for FILES.LAST_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(byte[] lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.LAST_ACCESS_TIME
     *
     * @return the value of FILES.LAST_ACCESS_TIME
     *
     * @mbggenerated
     */
    public byte[] getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.LAST_ACCESS_TIME
     *
     * @param lastAccessTime the value for FILES.LAST_ACCESS_TIME
     *
     * @mbggenerated
     */
    public void setLastAccessTime(byte[] lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.RECOVER_TIME
     *
     * @return the value of FILES.RECOVER_TIME
     *
     * @mbggenerated
     */
    public byte[] getRecoverTime() {
        return recoverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.RECOVER_TIME
     *
     * @param recoverTime the value for FILES.RECOVER_TIME
     *
     * @mbggenerated
     */
    public void setRecoverTime(byte[] recoverTime) {
        this.recoverTime = recoverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.TRANSACTION_COUNTER
     *
     * @return the value of FILES.TRANSACTION_COUNTER
     *
     * @mbggenerated
     */
    public byte[] getTransactionCounter() {
        return transactionCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.TRANSACTION_COUNTER
     *
     * @param transactionCounter the value for FILES.TRANSACTION_COUNTER
     *
     * @mbggenerated
     */
    public void setTransactionCounter(byte[] transactionCounter) {
        this.transactionCounter = transactionCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.TABLE_ROWS
     *
     * @return the value of FILES.TABLE_ROWS
     *
     * @mbggenerated
     */
    public byte[] getTableRows() {
        return tableRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.TABLE_ROWS
     *
     * @param tableRows the value for FILES.TABLE_ROWS
     *
     * @mbggenerated
     */
    public void setTableRows(byte[] tableRows) {
        this.tableRows = tableRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.AVG_ROW_LENGTH
     *
     * @return the value of FILES.AVG_ROW_LENGTH
     *
     * @mbggenerated
     */
    public byte[] getAvgRowLength() {
        return avgRowLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.AVG_ROW_LENGTH
     *
     * @param avgRowLength the value for FILES.AVG_ROW_LENGTH
     *
     * @mbggenerated
     */
    public void setAvgRowLength(byte[] avgRowLength) {
        this.avgRowLength = avgRowLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.DATA_LENGTH
     *
     * @return the value of FILES.DATA_LENGTH
     *
     * @mbggenerated
     */
    public byte[] getDataLength() {
        return dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.DATA_LENGTH
     *
     * @param dataLength the value for FILES.DATA_LENGTH
     *
     * @mbggenerated
     */
    public void setDataLength(byte[] dataLength) {
        this.dataLength = dataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.MAX_DATA_LENGTH
     *
     * @return the value of FILES.MAX_DATA_LENGTH
     *
     * @mbggenerated
     */
    public byte[] getMaxDataLength() {
        return maxDataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.MAX_DATA_LENGTH
     *
     * @param maxDataLength the value for FILES.MAX_DATA_LENGTH
     *
     * @mbggenerated
     */
    public void setMaxDataLength(byte[] maxDataLength) {
        this.maxDataLength = maxDataLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.INDEX_LENGTH
     *
     * @return the value of FILES.INDEX_LENGTH
     *
     * @mbggenerated
     */
    public byte[] getIndexLength() {
        return indexLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.INDEX_LENGTH
     *
     * @param indexLength the value for FILES.INDEX_LENGTH
     *
     * @mbggenerated
     */
    public void setIndexLength(byte[] indexLength) {
        this.indexLength = indexLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.CREATE_TIME
     *
     * @return the value of FILES.CREATE_TIME
     *
     * @mbggenerated
     */
    public byte[] getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.CREATE_TIME
     *
     * @param createTime the value for FILES.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(byte[] createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.UPDATE_TIME
     *
     * @return the value of FILES.UPDATE_TIME
     *
     * @mbggenerated
     */
    public byte[] getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.UPDATE_TIME
     *
     * @param updateTime the value for FILES.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(byte[] updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.CHECK_TIME
     *
     * @return the value of FILES.CHECK_TIME
     *
     * @mbggenerated
     */
    public byte[] getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.CHECK_TIME
     *
     * @param checkTime the value for FILES.CHECK_TIME
     *
     * @mbggenerated
     */
    public void setCheckTime(byte[] checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.CHECKSUM
     *
     * @return the value of FILES.CHECKSUM
     *
     * @mbggenerated
     */
    public byte[] getChecksum() {
        return checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.CHECKSUM
     *
     * @param checksum the value for FILES.CHECKSUM
     *
     * @mbggenerated
     */
    public void setChecksum(byte[] checksum) {
        this.checksum = checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILES.EXTRA
     *
     * @return the value of FILES.EXTRA
     *
     * @mbggenerated
     */
    public byte[] getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILES.EXTRA
     *
     * @param extra the value for FILES.EXTRA
     *
     * @mbggenerated
     */
    public void setExtra(byte[] extra) {
        this.extra = extra;
    }
}