package com.example.demo.entity;

public class FilepermissionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filepermissions.DepartmentID
     *
     * @mbggenerated
     */
    private Integer departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filepermissions.FileID
     *
     * @mbggenerated
     */
    private Integer fileid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filepermissions.DepartmentID
     *
     * @return the value of filepermissions.DepartmentID
     *
     * @mbggenerated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filepermissions.DepartmentID
     *
     * @param departmentid the value for filepermissions.DepartmentID
     *
     * @mbggenerated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filepermissions.FileID
     *
     * @return the value of filepermissions.FileID
     *
     * @mbggenerated
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filepermissions.FileID
     *
     * @param fileid the value for filepermissions.FileID
     *
     * @mbggenerated
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }
}