package com.example.demo.mapper;

import com.example.demo.entity.Department;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DepartmentsMapper {
    int insertDepartment(String departmentName);
    int deleteByPrimaryKey(Integer departmentid);
    int updateDepartmentNameById(Integer departmentId, String departmentName);
    int deleteDepartmentByName(String departmentName);
    List<Department> getDepartmentsByName(String departmentName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated
     */
    Department selectByPrimaryKey(Integer departmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Department record);

    List<Department> getAllDepartments();

    List<Department> selectdepartment(Integer departmentid);
}