package com.example.demo.mapper;

import com.example.demo.entity.Filereceptions;
import com.example.demo.entity.FilereceptionsKey;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FilereceptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filereceptions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FilereceptionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filereceptions
     *
     * @mbggenerated
     */
    int insert(Filereceptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filereceptions
     *
     * @mbggenerated
     */
    int insertSelective(Filereceptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filereceptions
     *
     * @mbggenerated
     */
    Filereceptions selectByPrimaryKey(FilereceptionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filereceptions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Filereceptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filereceptions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Filereceptions record);
}