package com.example.demo.mapper;

import com.example.demo.entity.Filepermissions;
import com.example.demo.entity.FilepermissionsKey;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FilePermissionsMapper {
    @Insert("INSERT INTO FilePermissions (FileID, DepartmentID, PermissionType) VALUES (#{fileId}, #{departmentId}, #{permissionType})")
    int insertFilePermission(String fileId, int departmentId, String permissionType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filepermissions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FilepermissionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filepermissions
     *
     * @mbggenerated
     */
    int insert(Filepermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filepermissions
     *
     * @mbggenerated
     */
    int insertSelective(Filepermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filepermissions
     *
     * @mbggenerated
     */
    Filepermissions selectByPrimaryKey(FilepermissionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filepermissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Filepermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filepermissions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Filepermissions record);
}