package com.example.demo.mapper;

import com.example.demo.dto.FileUploadDto;
import com.example.demo.entity.Files;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FilesMapper {
    int deleteFileById(String SerialNumber);
    int insertFile(FileUploadDto fileUploadDto);
    List<Files> getFilesByRoleAndDepartment(@Param("PermissionType") String PermissionType, @Param("departmentId") Integer departmentId);
    int updateFile(FileUploadDto fileUploadDto);
    FileUploadDto selectBySerialNumber(String SerialNumber);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int insert(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int insertSelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    Files selectByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Files record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Files record);
}